name: 'Get JSON by Key'
description: 'Simple GitHub Action to read a specified key from a JSON file and output to file'
author: 'Thada'
inputs:
  path:
    description: 'path to json file'
    required: true 
  prop_path:
    description: 'dot separated property key (e.g.: scripts.build)'
    required: true 
  output_path:
    description: 'path to output file'
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  color: "yellow"
  icon: "filter"  
